---
output:
  pdf_document:
    latex_engine: xelatex
    fig_caption: yes
  word_document: default
mainfont: Palatino
header-includes:
- \usepackage{caption}
- \captionsetup[figure]{labelformat=empty}
- \pagenumbering{gobble}
classoption: a4paper
---



<center>

![
**Figure S1. Monitoring framework of ecological community (as in Ushio 2022)**. (**a**) Locations of the five rice plots in 2017. (**b**) Research framework to generate quantitative environmental DNA time series and network reconstruction. (**c**) Ecological community network reconstructed by nonlinear time series. These figures were reproduced from Ushio (2022) _Proceedings of the Royal Society B_.
](../05_FigCode/00_ReformatFigs/Figure_S01.jpg){width=100%}

</center>


<center>

![
**Figure S2. Midge (_Chironomus kiiensis_) and _Globisporangium nunn_ used in the manipulation experiment in 2019**. (**a**) Larvae of midge (_Chironomus kiiensis_) naturally colonized in the rice plots. The larvae were manually removed by a commercial net with $\phi$ 1 mm mesh. (**b**) Microscopic image of _Globisporangium nunn_ (photo by M. Tojo). (**c**) _Globisporangium nunn_ was incubated in vermiculite and added to the rice plots. For the control and midge-removed treatments, vermiculite without _Globisporangium nunn_ was added. 
](../05_FigCode/00_ReformatFigs/Figure_S02.pdf){width=100%}

</center>


<center>

![
**Figure S3. Rice growth trajectory in 2019.** (**a**) Rice height, (**b**) growth rate, and (**c**) SPAD values of the rice during the growing season in 2019. Points indicate observed values, lines indicate mean trends, and gray lines indicate the field manipulation experiments. Colors indicate the treatments.
](../05_FigCode/00_ReformatFigs/Figure_S03.pdf){width=100%}

</center>


<center>

![
**Figure S4. Differential expression gene (DEG) patterns for each Wagner pot (Pot location-specific analysis).** DEG for (**a**) location 1, (**b**) location 2, and (**c**) location 3 for the control (CT) versus _Globisporangium nunn_-added (GN) treatments. (**d**-**f**) DEG analysis for the control versus _Chironomus kiiensis_-removed (CK) treatments for rice grown at locations 1-3. Red and blue points indicate significant up- and down-regulated genes, respectively. Upper and lower dashed lines indicate $\log_2(1.5)$ and $-\log_2(1.5)$, respectively.
](../05_FigCode/00_ReformatFigs/Figure_S04.jpg){width=100%}

</center>


